name: Manual Docs Publish

permissions:
    id-token: write
    contents: write
    pages: write

on: workflow_dispatch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
            - name: Setup Yarn v3
              run: |
                  corepack enable
                  corepack prepare yarn@stable --activate
            - name: Install dependencies
              run: yarn install --immutable
            - name: Build
              run: yarn run build
            - name: Build docs
              run: |
                  yarn run generate-api-docs
                  yarn run docs:build
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./docs/.vitepress/dist/"
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
